##############################################################################
# General

[[plugins]]
repository = 'tpope/vim-repeat'

[[plugins]]
repository = 'tpope/vim-unimpaired'
mappings = [['n', '[', ']', 'co']]

[[plugins]]
repository = 'ciaranm/securemodelines'
filetypes = 'all'


##############################################################################
# Shell

[[plugins]]
repository = 'tpope/vim-eunuch'
commands = ['Remove', 'Move', 'Rename', 'Mkdir']

[[plugins]]
repository = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
mappings = '<Plug>'
explorer = 1

  [plugins.commands]
  name = ['VimFiler', 'VimFilerExplorer']
  complete = 'customlist,vimfiler#complete'

[[plugins]]
repository = 'tpope/vim-dispatch'
commands = ['Dispatch', 'Dispatch!', 'Make', 'Make!']

[[plugins]]
repository = 'tyru/open-browser.vim'
mappings = '<Plug>'


##############################################################################
# UI

[[plugins]]
repository = 't9md/vim-choosewin' # visual window selection
mappings = '<Plug>'

[[plugins]]
repository = 'regedarek/ZoomWin' # zoom in/out a split
mappings = [['nox', '<C-w>o']]

[[plugins]]
repository = 'junegunn/goyo.vim' # distraction free editing
commands = 'Goyo'
gui = 1

[[plugins]]
repository = 'junegunn/limelight.vim' # focused writing
commands = 'Limelight'

[[plugins]]
repository = 'kergoth/vim-hilinks' # debug syntax highlighting
commands = ['HLT', 'HLT!']


##############################################################################
# Search and Navigation

[[plugins]]
repository = 'matchit.zip'
mappings = [['nox', '%', 'g%']]

[[plugins]]
repository = 'justinmk/vim-sneak'
depends = 'tpope/vim-repeat'
mappings = [['nox', '<Plug>Sneak']]

[[plugins]]
repository = 'Shougo/unite.vim'

  [plugins.commands]
  name = [
    'Unite',
    'UniteWithBufferDir',
    'UniteWithCurrentDir',
    'UniteWithProjectDir',
    'UniteWithInputDirectory',
    'UniteWithCursorWord',
  ]
  complete = 'customlist,unite#complete#source'

[[plugins]]
repository = 'Shougo/unite-help'

[[plugins]]
repository = 'Shougo/unite-outline'

[[plugins]]
repository = 'tsukkee/unite-tag'

[[plugins]]
repository = 'Shougo/neomru.vim'
unite_sources = ['file_mru', 'directory_mru']

##############################################################################
# Text Objects

[[plugins]]
repository = 'kana/vim-textobj-user'

[[plugins]]
repository = 'kana/vim-textobj-line' # line
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'al', 'il']]

[[plugins]]
repository = 'kana/vim-textobj-entire' # whole buffer
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'ae', 'ie']]

[[plugins]]
repository = 'saaguero/vim-textobj-pastedtext' # last pasted text
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'gb']]

[[plugins]]
repository = 'kana/vim-textobj-lastpat' # last search pattern (fwd/backwars)
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'a/', 'i/', 'a?', 'i?']]

[[plugins]]
repository = 'kana/vim-textobj-indent' # contiguous lines with indent >= cur line
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'ai', 'ii', 'aI', 'iI']]

[[plugins]]
repository = 'beloglazov/vim-textobj-quotes' # region between nearest quotes (any kind)
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'aq', 'iq']]

[[plugins]]
repository = 'rhysd/vim-textobj-anyblock' # ab  ib  (quotes, (), {}, [] and <>)
mappings = [['ox', 'ab', 'ib', '<Plug>(textobj-anyblock']]

[[plugins]]
repository = 'kana/vim-textobj-function' # function (C, Java, VimL, JS)
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'af', 'if']]
on_source = ['vim-textobj-function-javascript']

[[plugins]]
repository = 'thinca/vim-textobj-function-javascript'

[[plugins]]
repository = 'sgur/vim-textobj-parameter' # parameter (in comma-delimited lists)
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'a,', 'i,']]

[[plugins]]
repository = 'glts/vim-textobj-comment' # comment
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'ac', 'ic']]

[[plugins]]
repository = 'Julian/vim-textobj-variable-segment' # a_segment_of anyVarName
depends = 'kana/vim-textobj-user'
mappings = [['ox', 'av', 'iv']]

##############################################################################
# Editing and Formatting

[[plugins]]
repository = 'godlygeek/tabular'
commands = ['Tabularize']

[[plugins]]
repository = 'tpope/vim-endwise' # auto-closes control blocks in insert mode
insert = 1
focus = 1

[[plugins]]
repository = 'Raimondi/delimitMate' # auto-closes quotes, parens, etc. in insert mode
insert = 1
focus = 1

[[plugins]]
repository = 'tpope/vim-commentary.git' # toggle comments with gc{textobj}
mappings = [['nx', 'gc']]

[[plugins]]
repository = 'tpope/vim-abolish'
depends = 'tpope/vim-repeat'
commands = ['Abolish', 'Subvert', 'S'] # :Subvert is a powerful search/replace command
mappings = [['n', 'cr']] # crs to_snake, crm ToMixed, crc toCamel, cru TO_UPPERCASE

[[plugins]]
repository = 'kana/vim-operator-user'

[[plugins]]
repository = 'kana/vim-operator-replace' # <C-p> pastes over textobjs
depends = 'kana/vim-operator-user'
mappings = [['nx', '<Plug>(operator-replace)']]

[[plugins]]
repository = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
mappings = '<Plug>'

[[plugins]]
repository = 'terryma/vim-multiple-cursors' # <C-n> creates multiple cursors in normal mode
mappings = [['nx', '<C-n>']]

[[plugins]]
repository = 'junegunn/vim-easy-align'
mappings = '<Plug>(EasyAlign)'

[[plugins]]
repository = 'Chiel92/vim-autoformat' # integrates external formatting tools
disabled = 1


##############################################################################
# Code Completion and Snippets

[[plugins]]
repository = 'Valloric/YouCompleteMe'
build = './install.py --clang-completer --system-libclang --system-boost'
depends = 'SirVer/ultisnips'
augroup = 'youcompletemeStart'
filetypes = ['c', 'cpp', 'objc', 'objcpp']
insert = 1
focus = 1

[[plugins]]
repository = 'rdnetto/YCM-Generator'
commands = ['YcmGenerateConfig', 'CCGenerateConfig']


##############################################################################
# Git

[[plugins]]
repository = 'tpope/vim-fugitive'
augroup = 'fugitive'
commands = [
  'Git', 'Git!', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge', 'Gpull',
  'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog', 'Gllog', 'Gedit', 'Gsplit',
  'Gvsplit', 'Gtabedit', 'Gpedit', 'Gsplit!', 'Gvsplit!', 'Gtabedit!',
  'Gpedit!', 'Gread', 'Gread!', 'Gwrite', 'Gwrite', 'Gwq', 'Gwq!', 'Gdiff',
  'Gsdiff', 'Gvdiff', 'Gmove', 'Gremove', 'Gblame',
]
focus = 1

[[plugins]]
repository = 'airblade/vim-gitgutter'
commands = ['GitGutterToggle']


##############################################################################
# Testing

[[plugins]]
repository = 'janko-m/vim-test'
depends = 'tpope/vim-dispatch'
commands = ['TestNearest', 'TestFile', 'TestSuite', 'TestLast', 'TestVisit']


##############################################################################
# Code Analysis

[[plugins]]
repository = 'scrooloose/syntastic'
commands = [
  'SyntasticCheck', 'SyntasticStatuslineFlag',
  'SyntasticToggleMode', 'SyntasticInfo'
]

##############################################################################
# C, C++ and Objective C

[[plugins]]
repository = 'rhysd/vim-clang-format'
depends = 'kana/vim-operator-user'
filetypes = ['c', 'cpp', 'objc', 'objcpp']
commands = ['ClangFormat', 'ClangFormatAutoToggle']
mappings = '<Plug>(operator-clang-format)'

[[plugins]]
repository = 'jeaye/color_coded'
filetypes = ['c', 'cpp', 'objc', 'objcpp']
build_commands = ['cmake', 'make']
build = 'cmake . && make && make install'
gui = 1


##############################################################################
# JavaScript

[[plugins]]
repository = 'pangloss/vim-javascript'
filetypes = 'javascript'

[[plugins]]
repository = 'marijnh/tern_for_vim'
filetypes = 'javascript'
build = 'npm install'

[[plugins]]
repository = 'othree/javascript-libraries-syntax.vim'
filetypes = 'javascript'

[[plugins]]
repository = 'elzr/vim-json'
filetypes = ['javascript', 'json']

[[plugins]]
repository = 'mxw/vim-jsx'
filetypes = 'javascript'
disabled = 1


##############################################################################
# Lua

[[plugins]]
repository = 'tbastos/vim-lua'
filetypes = 'lua'


##############################################################################
# Text / Markup / Web

[[plugins]]
repository = 'cespare/vim-toml'
filetypes = 'toml'

[[plugins]]
repository = 'rcmdnk/vim-markdown'
depends = 'godlygeek/tabular'
filetypes = 'markdown'

[[plugins]]
repository = 'kannokanno/previm'
commands = 'PrevimOpen'

[[plugins]]
repository = 'othree/html5.vim'
filetypes = 'html'

[[plugins]]
repository = 'ap/vim-css-color'
filetypes = ['css','scss','sass','less']

[[plugins]]
repository = 'hail2u/vim-css3-syntax'
filetypes = ['css','scss','sass']

