##############################################################################
# General

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-unimpaired'
on_map = [['n', '[', ']', 'co']]

[[plugins]]
repo = 'ciaranm/securemodelines'
on_ft = 'all'


##############################################################################
# Shell

[[plugins]]
repo = 'tpope/vim-eunuch'
on_cmd = ['Remove', 'Move', 'Rename', 'Mkdir']

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'Shougo/unite.vim'
on_map = '<Plug>'
explorer = 1

  [plugins.commands]
  name = ['VimFiler', 'VimFilerExplorer']
  complete = 'customlist,vimfiler#complete'

[[plugins]]
repo = 'tpope/vim-dispatch'
on_cmd = ['Dispatch', 'Dispatch!', 'Make', 'Make!', 'Start', 'Start!', 'Copen', 'Copen!']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>'


##############################################################################
# UI

[[plugins]]
repo = 'moll/vim-bbye'
on_cmd = ['Bdelete']

[[plugins]]
repo = 't9md/vim-choosewin' # visual window selection
on_map = '<Plug>'

[[plugins]]
repo = 'mbbill/undotree'
on_cmd = ['UndotreeToggle']

[[plugins]]
repo = 'regedarek/zoomwin' # zoom in/out a split
on_map = [['nox', '<c-w>o']]

[[plugins]]
repo = 'junegunn/goyo.vim' # distraction free editing
on_cmd = 'Goyo'
gui = 1

[[plugins]]
repo = 'junegunn/limelight.vim' # focused writing
on_cmd = 'Limelight'

[[plugins]]
repo = 'kergoth/vim-hilinks' # debug syntax highlighting
on_cmd = ['HLT', 'HLT!']


##############################################################################
# Search and Navigation

[[plugins]]
repo = 'matchit.zip'
on_map = [['nox', '%', 'g%']]

[[plugins]]
repo = 'justinmk/vim-sneak'
depends = 'tpope/vim-repeat'
on_map = [['nox', '<Plug>Sneak']]

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

##############################################################################
# Text Objects

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-line' # line
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'al', 'il']]

[[plugins]]
repo = 'kana/vim-textobj-entire' # whole buffer
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'ae', 'ie']]

[[plugins]]
repo = 'saaguero/vim-textobj-pastedtext' # last pasted text
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'gb']]

[[plugins]]
repo = 'kana/vim-textobj-lastpat' # last search pattern (fwd/backwars)
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'a/', 'i/', 'a?', 'i?']]

[[plugins]]
repo = 'kana/vim-textobj-indent' # contiguous lines with indent >= cur line
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'ai', 'ii', 'aI', 'iI']]

[[plugins]]
repo = 'beloglazov/vim-textobj-quotes' # region between nearest quotes (any kind)
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'aq', 'iq']]

[[plugins]]
repo = 'rhysd/vim-textobj-anyblock' # ab  ib  (quotes, (), {}, [] and <>)
on_map = [['ox', 'ab', 'ib', '<Plug>(textobj-anyblock']]

[[plugins]]
repo = 'kana/vim-textobj-function' # function (C, Java, VimL, JS)
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'af', 'if']]
on_source = ['vim-textobj-function-javascript']

[[plugins]]
repo = 'thinca/vim-textobj-function-javascript'

[[plugins]]
repo = 'sgur/vim-textobj-parameter' # parameter (in comma-delimited lists)
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'a,', 'i,']]

[[plugins]]
repo = 'glts/vim-textobj-comment' # comment
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'ac', 'ic']]

[[plugins]]
repo = 'Julian/vim-textobj-variable-segment' # a_segment_of anyVarName
depends = 'kana/vim-textobj-user'
on_map = [['ox', 'av', 'iv']]

##############################################################################
# Editing and Formatting

[[plugins]]
repo = 'godlygeek/tabular'
on_cmd = ['Tabularize']

[[plugins]]
repo = 'tpope/vim-endwise' # auto-closes control blocks in insert mode
on_i = 1
focus = 1

[[plugins]]
repo = 'Raimondi/delimitMate' # auto-closes quotes, parens, etc. in insert mode
on_i = 1
focus = 1

[[plugins]]
repo = 'tpope/vim-commentary.git' # toggle comments with gc{textobj}
on_map = [['nx', 'gc']]

[[plugins]]
repo = 'tpope/vim-abolish'
depends = 'tpope/vim-repeat'
on_cmd = ['Abolish', 'Subvert', 'S'] # :Subvert is a powerful search/replace command
on_map = [['n', 'cr']] # crs to_snake, crm ToMixed, crc toCamel, cru TO_UPPERCASE

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace' # <C-p> pastes over textobjs
depends = 'kana/vim-operator-user'
on_map = [['nx', '<Plug>(operator-replace)']]

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'kana/vim-operator-user'
on_map = '<Plug>'

[[plugins]]
repo = 'terryma/vim-multiple-cursors' # <C-n> creates multiple cursors in normal mode
on_map = [['nx', '<C-n>']]

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>(EasyAlign)'

[[plugins]]
repo = 'Chiel92/vim-autoformat' # integrates external formatting tools
disabled = 1


##############################################################################
# Code Completion and Snippets

[[plugins]]
repo = 'Valloric/YouCompleteMe'
build = './install.py --clang-completer --system-boost'
depends = 'SirVer/ultisnips'
augroup = 'youcompletemeStart'
on_ft = ['c', 'cpp', 'objc', 'objcpp']
on_i = 1
focus = 1

##############################################################################
# Git

[[plugins]]
repo = 'tpope/vim-fugitive'
augroup = 'fugitive'
on_cmd = [
  'Git', 'Git!', 'Gcd', 'Glcd', 'Gstatus', 'Gcommit', 'Gmerge', 'Gpull',
  'Gpush', 'Gfetch', 'Ggrep', 'Glgrep', 'Glog', 'Gllog', 'Gedit', 'Gsplit',
  'Gvsplit', 'Gtabedit', 'Gpedit', 'Gsplit!', 'Gvsplit!', 'Gtabedit!',
  'Gpedit!', 'Gread', 'Gread!', 'Gwrite', 'Gwrite', 'Gwq', 'Gwq!', 'Gdiff',
  'Gsdiff', 'Gvdiff', 'Gmove', 'Gremove', 'Gblame',
]
focus = 1

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_cmd = ['GitGutterToggle']


##############################################################################
# Testing

[[plugins]]
repo = 'janko-m/vim-test'
depends = 'tpope/vim-dispatch'
on_cmd = ['TestNearest', 'TestFile', 'TestSuite', 'TestLast', 'TestVisit']


##############################################################################
# Code Analysis

[[plugins]]
repo = 'scrooloose/syntastic'
on_cmd = [
  'SyntasticCheck', 'SyntasticStatuslineFlag',
  'SyntasticToggleMode', 'SyntasticInfo'
]

##############################################################################
# C, C++ and Objective C

[[plugins]]
repo = 'rhysd/vim-clang-format'
depends = 'kana/vim-operator-user'
on_ft = ['c', 'cpp', 'objc', 'objcpp']
on_cmd = ['ClangFormat', 'ClangFormatAutoToggle']
on_map = '<Plug>(operator-clang-format)'

[[plugins]]
repo = 'jeaye/color_coded'
on_ft = ['c', 'cpp', 'objc', 'objcpp']
build_commands = ['cmake', 'make']
build = 'cmake . && make && make install'
gui = 1


##############################################################################
# JavaScript

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = 'javascript'
build = 'npm install'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['javascript', 'json']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
disabled = 1


##############################################################################
# Lua

[[plugins]]
repo = 'tbastos/vim-lua'
on_ft = 'lua'

##############################################################################
# OpenGL

[[plugins]]
repo = 'tikhomirov/vim-glsl'
on_ft = ['glsl', 'frag', 'geom', 'vert']

##############################################################################
# Text / Markup / Web

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
depends = 'godlygeek/tabular'
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css','scss','sass','less']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css','scss','sass']

