##############################################################################
# Core Bundles

[[plugins]]
repository = 'Shougo/neobundle.vim'
fetch = 1

[[plugins]]
repository = 'Shougo/vimproc.vim'
build = 'make'

##############################################################################
# Bundles needed at startup

[[plugins]]
repository = 'mhinz/vim-startify'

[[plugins]]
repository = 'qpkorr/vim-bufkill'

[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'jwhitley/vim-colors-solarized' # solarized fork that fixes sign column bg

[[plugins]]
repository = 'reedes/vim-colors-pencil'

##############################################################################
# Bundles that break on lazy loading

[[plugins]]
repository = 'SirVer/ultisnips'
unite_sources = ['ultisnips']

