[[plugins]]
repository = 'Shougo/neobundle.vim'
fetch = 1

[[plugins]]
repository = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repository = 'mhinz/vim-startify'

##############################################################################
# UI

[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'jwhitley/vim-colors-solarized' # solarized fork that fixes sign column bg

[[plugins]]
repository = 'reedes/vim-colors-pencil'

##############################################################################
# Bundles that don't support lazy loading

[[plugins]]
repository = 'SirVer/ultisnips'

