set -g mouse on
set -g default-terminal 'tmux-256color'
set -g terminal-overrides ',xterm-256color:RGB'

set -ga terminal-features ",*:RGB"
setenv -g COLORTERM "truecolor"
set -ga terminal-features ",*:hyperlinks"

set -g base-index 1              # start indexing windows at 1 instead of 0
set -g default-terminal "${TERM}"
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top
setw -g mode-keys vi

# Bindings (prefix: Ctrl+Space)
# ========

unbind C-b
set -g prefix C-space
bind C-space send-prefix
bind ^D detach
bind * list-clients
bind l refresh-client
bind ^L refresh-client

bind S choose-session
bind R source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux.conf"
bind K send-keys "clear"\; send-keys "Enter"

bind ^C new-window -c "$HOME"
bind ^A last-window
bind ^W list-windows

unbind %
bind s split-window -h
bind v split-window -v

# no delay for escape key press
set -sg escape-time 0

# vim style copy/paste
unbind p
bind p paste-buffer
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection

# vim style pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# shift-arrow keys without prefix key to switch panes
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D

# shift-arrow keys without prefix key to switch panes
bind -n C-S-Left resize-pane -L
bind -n C-S-Right resize-pane -R
bind -n C-S-Up resize-pane -U
bind -n C-S-Down resize-pane -D

# Plugins
# =======

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

set -g @continuum-restore 'on'
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'
set -g @resurrect-strategy-nvim 'session'

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Initialize TPM (loads all plugins).
run '~/.dotfiles/vendor/tpm/tpm'
